### ISSUE TITLE
Addition to RELEASE files

### ISSUE THREAD

**Issue by mdmoo1978** [areaDetector/areaDetector#14]
I would like to propose a change to RELEASE file to add RELEASE.local.$(EPICS_HOST_ARCH), after RELEASE.local. This would also require a change to all driver's RELEASE files.

The change would turn the current RELEASE.local would have drivers that work on all architectures and RELEASE.local.$(EPICS_HOST_ARCH) would have the drivers that only work on specific architectures.
#### **For Example:**
ADPROCILIA would be in RELEASE.local, but ADPERKINELMER could only be in the .windows versions. 

This can reduce the need to modify the RELEASE.local files as you are building for multiple architectures. It is a small change, but impacts the entire areaDetector build system. For me it handles that fact that I don't need to build marCCD for anything but linux-x86, since my marCCD systems don't support linux-86_64, while still allowing for a single configuration.

#### 1) Changes in <a href="https://github.com/areaDetector/areaDetector/blob/master/configure/">areaDetector/configure/</a>
  * [ ] Modify <a href="https://github.com/areaDetector/areaDetector/blob/master/configure/RELEASE">areaDetector/configure/RELEASE</a> to add -include $(TOP)/configure/RELEASE.local.$(EPICS_HOST_ARCH) after line 8.
  * [ ] Add EXAMPLE_RELEASE.local.$(EPICS_HOST_ARCH) (this might be optional)

#### 2) Changes in all Drivers
  * [ ] Modify all driver's configure/RELEASE</a> to add -include $(TOP)/configure/RELEASE.local.$(EPICS_HOST_ARCH) after line 9.
  * [ ] Modify all driver's ioc/___IOC/configure/RELEASE</a> to add -include $(TOP)/configure/RELEASE.local.$(EPICS_HOST_ARCH) after line 11.

If it sounds good to people, I am happy to make the changes since it would be helpful to me when I am doing my builds.

**Comment by MarkRivers** [comment]
I like this idea and in fact was about to do it myself because, for example I can build ADPointGrey on linux-x86_64, but not on linux-x86_64-gcc42.  So I want to comment ADPOINTGREY in RELEASE.local  and uncomment it in RELEASE.local.linux-x86.   I agree with your Changes Required item 1).  I have done that and will commit soon.  However, I do not think that your item 2) Changes in all Drivers is needed or useful.  The only thing the RELEASE.local* files do is define the path to a particular detector, e.g. ADPOINTGREY.  If the string is not defined then the top-level areaDetector/Makefile will not build that detector.  The only place the string ADPOINTGREY is used is in that top-level Makefile, not in the Makefiles in each detector directory.  If I cd to ADPointGrey and type "make" then the build system will try to build for the current EPICS_HOST_ARCH, and presumably I did that deliberately so it is fine.  In fact when I am in the ADPointGrey directory item 2) would not prevent the build system from building on an arch that was not defined in a RELEASE.local* file, since the Makefiles in the detector directories do not use the ADPOINTGREY variable at all.

**Comment by mdmoo1978** [comment]
I agree with you that if you move into the ADPOINTGREY directory it will try to build for the host current EPICS_HOST_ARCH. The issue I have run into is if my directory name is not ADPointGrey (as it is defined in ioc/../configure/RELEASE), but ADPointGrey-R-2-1. By adding it to at least the ioc/../configure/RELEASE it would fix that.

**Comment by MarkRivers** [comment]
I see your problem.  But I don't like the solution because ADPointGrey should be able to be built without even having a top-level areaDetector directory.  A better solution is to use a relative path to find  the Point Grey top-level directory.  I just made this change to iocs/pointGreyIOC/configure/RELEASE and it worked for me.

-ADPOINTGREY=$(AREA_DETECTOR)/ADPointGrey
+ADPOINTGREY_TOP=$(TOP)/../..

We can't redefine the variable ADPOINTGREY which seems like the easiest thing to do, because that results in a CHECK_RELEASE error since it is defined differently in areaDetector/configure/RELEASE.local.  So instead we use a new variable that uses a relative path.  Make now searches that path and finds the needed files.

**Comment by mdmoo1978** [comment]
I can try it, but I want to go back to something you said:
>because ADPointGrey should be able to be built without even having a top-level areaDetector directory

What exactly do you mean by this? 
1. Are you saying that you want to be able to go into ADPointGrey (which is inside of the areaDetector directory/make system) and just make? 
2. There doesn't need to be areaDetector directory and RELEASE files and make system to build ADPointGrey?

If it is number 2, that is fine, but I have never tried to do that. I would need to think about how that works, since the ioc RELEASE file looks for RELEASE_PRODS.local (and other files) in the areaDetector directory.

The one thing that your change:
>-ADPOINTGREY=$(AREA_DETECTOR)/ADPointGrey
+ADPOINTGREY_TOP=$(TOP)/../..

I think this assumes is that you are building the IOC in the ADPointGrey directory and I'm not sure that is a requirement that should be set. I know it is how I do it, but I'm not sure it is the way everyone wants to build there IOCs. Maybe others can chime in on how they build the IOCs?

**Comment by ulrikpedersen** [comment]
FWIW, at Diamond we build all areaDetector modules as individual support modules - we have a whole infrastructure (networked file systems, automated build servers, source repository servers, etc) setup around that model. We don't use (and cannot) a top-level areaDetector module in this environment. The areaDetector top-level module was inspired by the synApps model: each module can be built on it's own, but if you wish you can get everything packaged up neatly in the synApps distribution (we also don't use the synApps top-level package).

Our production IOCs are always built outside of the support modules - in an entirely different branch of our directory tree which is organised around beamlines (each beamline have their own set of IOCs built). Developers sometimes for convenience build example/test/demo IOCs inside the support modules, but we often don't build those as part of our automated release procedure. 

A few modules which we export/collaborate on has IOCs built into the module - but we only use those for development/testing and not for beamlines in production.

**Comment by kmpeters** [comment]
> I know it is how I do it, but I'm not sure it is the way everyone wants to build there IOCs. Maybe others can chime in on how they build the IOCs?

I build and deploy IOCs outside of the support modules.  I frequently need to build areaDetector drivers outside of the areaDetector directory.

**Comment by mdmoo1978** [comment]
@ulrikpedersen and @kmpeters does the change that @MarkRivers detailed above impact your ability to build IOC outside of the support modules? Or do you not care, because you just have a custom IOC building system that you bring in the support when you need it?

I work in the APS Detector Pool and our needs are very different from most groups. We can't rely on network files systems or most of the other tools you have, since we can't even assume we will have a network connection. Our detectors move all around the APS ring and have to work right away. We use the "example" IOCs, which are stored locally on each systems. Almost all of our computer system have a full set of areaDetector IOC and most of our computer system can control almost all of our detectors. This allows us flexibility with our system and reduces the down time if there are issues with a computer system. We also try to use tagged versions whenever possible, for some level of stability (which is why I care about this).

**Comment by MarkRivers** [comment]
>1. Are you saying that you want to be able to go into ADPointGrey (which is inside of the areaDetector directory/make system) and just make? 
2. There doesn't need to be areaDetector directory and RELEASE files and make system to build ADPointGrey?

>If it is number 2, that is fine, but I have never tried to do that. I would need to think about how that works, since the ioc RELEASE file looks for RELEASE_PRODS.local (and other files) in the areaDetector directory.

Number 1) above is certainly something one does all the time, and it works with ADPointGrey as distributed assuming there is a top-level areaDetector/configure directory that has been properly set up.

What I am saying is that we also want to support 2), i.e. no overlying areaDetector/configure directory.  That won't work with ADPointGrey as distributed, it requires creating ADPointGrey/configure/RELEASE.local and ADPointGrey/iocs/pointGreyIOC/configure/RELEASE.local which would contain the types of definitions are a normally done in the areaDetector/configure directory.  

But the current version of ADPointGrey/iocs/pointGreyIOC/configure/RELEASE is not good, because it hard-codes the name and path to the ADPointGrey directory.  As you point out you might rename this directory, or place it somewhere else.  By changing that RELEASE file to use a relative path to find the top-level of the ADPointGrey tree we improve things.

The one thing that your change:

>>-ADPOINTGREY=$(AREA_DETECTOR)/ADPointGrey
+ADPOINTGREY_TOP=$(TOP)/../..

>I think this assumes is that you are building the IOC in the ADPointGrey directory and I'm not sure that is a requirement that should be set. I know it is how I do it, but I'm not sure it is the way everyone wants to build there IOCs. Maybe others can chime in on how they build the IOCs?

I don't understand what you are saying.  The pointGreyIOC directory IS in the ADPointGrey directory tree.  If one moves that pointGreyIOC directory somewhere else then certainly one needs to edit the RELEASE file.  But we are not trying to fix that case, we are trying to make building the distributed ADPointGrey tree easy whether or not there is an overlying areaDetector directory.

**Comment by mdmoo1978** [comment]
Ok, I'm good with it.

**Comment by mp49** [comment]
That's what we do too. 

We're currently using:

ADCore
ADAndor
ADAndor3
ADnED
ADProsilica

and not the top level areaDetector. 

I just manage the RELEASE files by hand, and it avoids dealing with submodules.

Cheers,
Matt

Data Acquisition and Control Engineer
Spallation Neutron Source
Oak Ridge National Lab

**Comment by MarkRivers** [comment]
This issue was fixed by adding support for `areaDetector/configure/RELEASE.local.$(EPICS_HOST_ARCH)` and by using relative paths to the support module in the iocs/ directories.  For example:

    ADPOINTGREY=$(TOP)/../..
