### ISSUE TITLE
Question about repositories

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/areaDetector#34]
Kaz Gofron and Jakub Wlodjakub have written a new barcode reader plugin.  The question we are facing is how to incorporate this into the areaDetector project.  It is currently in Jakob's account on Github, and he would like to keep it there.

It seems there are 2 ways to do this:

1) The areaDetector project creates a fork of Jakub's private repository.  areaDetector users clone this, and push back to areaDetector project.  We create pull requests to Jakub's repository with our changes.  We can also do git pulls to merge Jakub's changes back into the areaDetector repository.

2) Jakub transfers the project to areaDetector, and then forks it to his private repository.  He then does git pull to merge our changes, and makes pull requests to get his changes into areaDetector.

What are other's thoughts on the best way to do this, both for this project and for similar ones going forward?

**Comment by ulrikpedersen** [comment]
Technically it doesn't really matter who has the 'original' repo and who has forks. Because merges, Pull Requests, etc. can be done across forks/originals in any direction and by anyone as long as the repos are publicly visible on github (i.e. not paid-for private/hidden repos).

So the main issue is really to decide who has the 'ownership' of the repo and that's more of a ... philosophical dicussion :-)

I would suggest option 1 as our (DLS) preferred way of doing this: we like to keep the ownership of our developed software in-house but happy to share by open-sourcing and using a forking work-flow - which then doesn't prevent the collaboration to move forward when we can't keep up. That works for all in my view.

However, on a related note, I also do have a small preference from dealing with repos from github 'organisations' rather than individuals personal github accounts. What happens to personal github accounts once people leave their synchrotron jobs for high-flying Silicon Valley tech? That's why we have the github.com/dls-controls organisation where we host our repos...

**Comment by prjemian** [comment]
Another aspect is where do the issues get created and managed.  In the
scenario where AD is the fork, usually that fork does not get to create
issues.That might confuse AD contributors.

Since we commit work against issues, I think this is important to resolve.

**Comment by MarkRivers** [comment]
Questions:

> Another aspect is where do the issues get created and managed.  In the
scenario where AD is the fork, usually that fork does not get to create
issues

Is that just a convention, or is it not possible to create issues on the fork?  If they are created on the fork will a pull request merge them back into the upstream?

> What happens to personal github accounts once people leave their synchrotron jobs for high-flying Silicon Valley tech? 

If the personal account disappeared could the AD repository then become the owner, i.e. it no longer had an upstream?

**Comment by ulrikpedersen** [comment]
> Is that just a convention, or is it not possible to create issues on the fork? If they are created on the fork will a pull request merge them back into the upstream?

Actually issues **can** be created on the fork (but you may have to specifically enable them in the repo settings). Issues and Pull Requests on forks only relate to the fork itself - so a fork can work completely independently of the original repo. If/when you wish to feed a bunch of changes upstream from the fork to the original repo then you can then just issue a PR in the appropriate direction (or to any other fork on github!)

That's why I say that technically there is little or no difference between forks and originals.

> If the personal account disappeared could the AD repository then become the owner, i.e. it no longer had an upstream?

When a public repo is deleted, one fork is chosen as the new parent repo (policy of how the choice is made is not clear): https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository

**Comment by kgofron** [comment]
We are migrating the NSLS2 areaDetector development to a 
https://github.com/epicsNSLS2-areaDetector

This is our staging area before it gets pulled into the main github.com/areaDetector site.
